### ISSUE TITLE
Browser console errors

### ISSUE THREAD

**Issue by jefflau** [makoto/blockparty#25]
Upon fixing a `export default` duplicate and running `truffle serve`, screen is blank (white) and I get these errors in the console:

```
Uncaught TypeError: Cannot read property '__reactInternalInstance$cl927kzfiem3mrd6kti5yzxgvi' of null
bluebird.js:1546Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at http://localhost:8080/app.js:202:40
    at Array.map (native)
    at Object.getDetail (http://localhost:8080/app.js:201:133)
    at new BountyInstruction (http://localhost:8080/app.js:119036:12)
    at http://localhost:8080/app.js:38880:19
    at measureLifeCyclePerf (http://localhost:8080/app.js:38660:13)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:8080/app.js:38879:17)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:8080/app.js:38865:22)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/app.js:38773:22)
    at Object.mountComponent (http://localhost:8080/app.js:31300:36)
    at ReactDOMComponent.mountChildren (http://localhost:8080/app.js:37980:45)
    at ReactDOMComponent._createInitialChildren (http://localhost:8080/app.js:34989:33)
    at ReactDOMComponent.mountComponent (http://localhost:8080/app.js:34814:13)
    at Object.mountComponent (http://localhost:8080/app.js:31300:36)
    at ReactDOMComponent.mountChildren (http://localhost:8080/app.js:37980:45)
    at ReactDOMComponent._createInitialChildren (http://localhost:8080/app.js:34989:33)
From previous event:
    at window.onload (http://localhost:8080/app.js:169:12)
bignumber.js:1209Uncaught BigNumber Error: new BigNumber() not a base 16 number: 
```

**Comment by makoto** [comment]
This was because `npm install` installs unnecessary contracts from zeppelin. Removing uncommited zeppelin contracts, `rm -rf build` and `truffle compile` solved the issue
